exclude: 'docs|node_modules|migrations|.envs|config|.git|.tox'
default_stages: [ commit ]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-symlinks
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-json
      - id: debug-statements
      - id: pretty-format-json
        files: (^|/)a/.+\.(py|html|sh|css|js|json)$
  - repo: https://github.com/myint/autoflake
    rev: 'v1.4'
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports' ]
  - repo: https://github.com/pycqa/flake8
    rev: main
    hooks:
      - id: flake8
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.0.2
    hooks:
      - id: pycln
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [ --settings-path=pyproject.toml ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
